(function(g){var window=this;var A2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Iz(a),kind:a.o,name:a.u,id:a.Ea,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},B2=function(a){return a.g?a.g.languageCode:a.i},ipa=function(a,b){var c=new g.Hz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},C2=function(a){if(!jpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(kpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},lpa=function(){this.i=[];
this.g=[]},D2=function(a,b){return b?a.g.concat(a.i):a.g},E2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.y)(b.Fq,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.y)(b.Fq,b))||c.push(b)}},F2=function(){g.H.call(this);
this.i=new lpa;this.u=[]},G2=function(a,b,c){F2.call(this,a);
this.g=null;this.u=b.hu;this.l=c},H2=function(){this.Ta=[]},I2=function(a,b,c,d,e,f){g.H.call(this);
this.I=a;this.o=b;this.A=new H2;this.g=null;this.F=d;this.O=f;this.i=this.l=null;this.D=c;this.B=e||!1;this.H=new g.N(this.qw,1E3,this);g.I(this,this.H);this.u=new g.hs(this);g.I(this,this.u);g.R(g.X(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.Zw):this.u.K(b,"seekcomplete",this.uF);this.Zw(b.getCurrentTime());this.qw()},J2=function(a,b){b-=a.o.dc();
var c=a.g;a.g=g.Va(a.D.rf(b).g);c!=a.g&&a.O&&a.O()},K2=function(a,b){var c=g.Ov(b,a.I,{}).Hb(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.vr(c,d,3,100).then((0,g.y)(a.YJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.ob(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.bb(c.Ta,e),g.bb(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.kb(c.Ta,e,0,d),g.kb(c.Ta,e+1,0,d)))},L2=function(a,b){F2.call(this,g.X(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.sz(g.X(this.B))&&!this.g.i},M2=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.dV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Hz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},mpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},N2=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.dV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},O2=function(a,b,c,d,e){F2.call(this,e||null);
c=c||g.Dq(a).hl||"";c=c.split("_").join("-");this.o=g.Fq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},P2=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.gE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},Q2=function(a,b,c,d,e){g.gE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},S2=function(a){a=void 0===a?{}:a;
var b="_"+R2++;return new Q2(0,0x8000000000000,0,b,a)},U2=function(a,b,c,d,e,f){var k={};
g.Sa(k,b);g.Sa(k,a.params);g.Sa(k,c);var l={};g.Sa(l,b.yb);a.params.yb&&g.Sa(l,a.params.yb);g.Sa(l,c.yb);k.yb=l;g.W.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.te?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.B=[];this.P=!1;this.o=a;this.V=this.R=null;this.Ra=e;this.Oa=f;this.D=null;this.X=.96*e;this.xa=.96*f;this.l=k;this.Ma=c;this.A=this.i["captions-text"];this.Ba=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Y=d/360*16;this.type=0;this.ka=this.Y*T2(l);a=new g.ns(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.tF,this);a.subscribe("dragmove",this.sF,this);a.subscribe("dragend",this.rF,this);this.va=this.na=0;b="";this.l.windowOpacity&&(a=C2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":npa[this.l.textAlign]};
this.Ba&&(a["border-radius"]=b?this.ka/8+"px":"");if(this.u=2==this.o.params.te||3==this.o.params.te)b=this.element,c="vertical-rl",1==this.l.eA&&(c="vertical-lr"),g.Pd&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.Ch(b,"-o-writing-mode",c),g.Ch(b,"-webkit-writing-mode",c),g.Ch(b,"writing-mode",c),g.Ch(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3==this.o.params.te&&(g.Ch(b,"text-orientation",""),g.Ch(b,"transform","rotate(180deg)"));g.Ch(this.element,a);switch(this.l.Mf){case 0:case 1:case 2:g.L(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},T2=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},V2=function(a,b){var c={},d=b.background?b.background:a.l.yb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.yb.backgroundOpacity;d=C2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ba&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ka/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*T2(b)+"px";d=1;e=b.color||a.l.yb.color;if(b.color||null!=b.textOpacity)e=C2(e),d=null==b.textOpacity?a.l.yb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.pu&&(k=e=b.pu);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.dr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.yb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ke&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.vD&&(c.visibility="hidden");1==b.xD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.uz||g.vz,3==a.o.params.te?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));1==b.YL&&(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",g.uz&&(c["font-weight"]="bold"));return c},W2=function(a){a.D=g.Vd("SPAN");
g.Ch(a.D,{display:"block"});g.L(a.D,"caption-visual-line");a.A.appendChild(a.D)},X2=function(a,b){var c=g.Vd("SPAN");
g.Ch(c,{display:"inline-block","white-space":"pre-wrap"});g.Ch(c,V2(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.Ch(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ch(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Y2=function(a,b,c){a.P=a.P||!!c;
var d={};g.Sa(d,a.l.yb);g.Sa(d,c||b.i);g.Sa(d,a.Ma.yb);(c=!a.D)&&W2(a);for(var e=a.R&&a.V&&g.bc(d,a.V)?a.R:X2(a,d),f=g.v(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(W2(a),e=X2(a,d)):m&&c&&(c=!1);n&&e.appendChild(f?g.Wd(n):n)}a.V=d;a.R=e;a.B.push(b)},Z2=function(){},a3=function(){this.o=this.i=this.mode=this.l=0;
this.u=new $2(this);this.A=new $2(this);this.g=[];this.clear()},opa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{ql:a,
rl:b,result:0};a=b3[a];b=b3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{ql:a,rl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ql:a,rl:b,result:2};return{ql:a,rl:b,result:3}},ppa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,c3(a.u,b,c,d))},qpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?ppa(a,d.ju,d.ku,b):1==d.type&&a.l&496&&c3(a.A,d.ju,d.ku,b)}a.g.length=0},d3=function(){this.g=0},e3=function(){this.i=this.l=this.g=0},f3=function(){this.timestamp=this.Ld=0},g3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new f3}this.g=this.i=this.row=0;this.style=new d3;this.u=a;this.o=0},h3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Ld){0==c&&(c=m,d=p);n=String.fromCharCode(r.Ld);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Ld||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Ld,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},vpa=function(a,b){switch(a){case 0:return rpa[(b&127)-32];
case 1:return spa[b&15];case 2:return tpa[b&31];case 3:return upa[b&31]}return 0},i3=function(a){return a.l[a.row][a.i]},j3=function(a,b,c){2<=b&&1<a.i&&(--a.i,i3(a).Ld=0);
var d=i3(a);d.timestamp=a.u.i+0;d.Ld=vpa(b,c);32>a.i&&a.i++},k3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Uf(a.l[c+e][f])},l3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},m3=function(a){a.row=0<a.g?a.g:1;
a.i=1;l3(a,0,15)},n3=function(a){this.o=a;
this.u=0;this.style=new d3;this.A=new g3(a);this.B=new g3(a);this.D=new g3(a);this.i=this.A;this.l=this.B;this.g=this.i},o3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:h3(d,c),m3(a.i),m3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(h3(d,c),l3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},p3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},q3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},$2=function(a){this.i=a;
this.g=new e3;this.u=0;this.l=new n3(a);this.A=new n3(a);this.o=this.l},c3=function(a,b,c,d){a.g.update();
b=opa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ql;c=b.rl;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&j3(a,0,b),c&96&&j3(a,0,c),0!=b&&0!=c&&3==a.style.g&&h3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;k3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));l3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:j3(b.g,0,32);break a;case 48:57==c?(d=b.g,i3(d).Ld=0,32>d.i&&d.i++):j3(b.g,1,c&15)}break;case 2:c&32&&j3(b.g,2,c&31);break;case 3:c&32&&j3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:p3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,i3(d).Ld=0);break;case 36:d=b.g;b=i3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:o3(b,2,d);break;case 38:o3(b,3,d);break;case 39:o3(b,4,d);break;case 40:j3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);m3(d);q3(b);break;case 43:q3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:h3(a,d)}l3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;h3(a,d);k3(a,b,b+1,a.g-1);l3(a,a.row,1)}break;case 46:l3(b.l,0,15);break;case 47:h3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,p3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},r3=function(){g.H.apply(this,arguments)},s3=function(a){r3.call(this);
this.l={};this.F={};this.H={};this.u="_"+R2++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},t3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},u3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},v3=function(a,b){var c=t3(a,b);
return void 0!=c?c:null},x3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return w3.test(c),c},y3=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.H[d]:a.A);d=v3(b,"mh");null!=d&&(c.Aq=d);d=v3(b,"ju");null!=d&&(c.textAlign=d);d=v3(b,"pd");null!=d&&(c.te=d);d=v3(b,"sd");null!=d&&(c.eA=d);d=x3(b,"wfc");null!=d&&(c.windowColor=d);d=t3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},z3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.F[d]);d=v3(b,"ap");null!=d&&(c.Mf=d);d=t3(b,"cc");null!=d&&(c.Cl=d);d=t3(b,"ah");null!=d&&(c.Le=d);d=t3(b,"rc");null!=d&&(c.uk=d);d=t3(b,"av");null!=d&&(c.yg=d);return c},A3=function(a,b,c,d){var e={};
g.Sa(e,z3(a,b));g.Sa(e,y3(a,b));d?g.bc(e,a.A)?(d=a.u,e=a.A):d="_"+R2++:d=b.getAttribute("id")||"_"+R2++;a=t3(b,"t")+c;b=t3(b,"d")||0x8000000000000;if(2==e.te||3==e.te)c=e.uk,e.uk=e.Cl,e.Cl=c;return new Q2(a,b,0,d,e)},B3=function(a,b,c,d,e,f,k){U2.call(this,a,b,c,d,e,f,k);
this.type=1},C3=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},D3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},E3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},F3=function(a,b){r3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new a3;this.g.l=1<<this.track},H3=function(a){if(g.v(a))return!1;
a=new C3(a,8,0);return G3(a)},G3=function(a){if(!(a.g<a.i.byteLength)||1380139777!=E3(a))return!1;
a.version=D3(a);if(1<a.version)return!1;D3(a);D3(a);D3(a);return!0},I3=function(a,b,c,d,e,f,k){U2.call(this,a,b,c,d,e,f,k);
g.L(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ca=0;this.M=NaN;this.ya=0;this.Ga=null;this.ia=new g.N(this.dK,433,this);g.I(this,this.ia)},wpa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},xpa=function(a){if(isNaN(a.M)){var b=a.l.Cl;
if(b){var c=g.Vd("SPAN");g.ee(c,"\u2013".repeat(b));g.Ch(c,V2(a,a.l.yb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},ypa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.eA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},J3=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.uk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(xpa(a),a.ya,wpa(a,a.A))},zpa=function(a,b){J3(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ca){var d=0<c&&0==a.ca;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.xo(a.ia));g.Ch(a.A,"transform",ypa(a,c));a.ca=c}J3(a)},K3=function(){r3.call(this)},L3=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ke=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new P2(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var r=e;g.I(r,p);r.i.push(p)}else r={},g.Sa(r,l),L3(a,b,c,d,e,!0,p,r,m)}},M3=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},N3=function(a,b,c,d){d=Object.assign({Aq:0},d);
return new Q2(a,b,c,"_"+R2++,d)},O3=function(a){g.H.call(this);
this.i=a;this.g=null},R3=function(a){g.RK.call(this,a);
this.u=g.X(a);this.l=a.getVideoData();this.xa=g.oK(a);this.I=a;var b=null,c=g.ip("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.To(c));this.aa=b;this.o={yb:{}};this.A={yb:{}};this.H=[];this.M={};this.V={};this.O=!1;this.na=g.eV(this.l,this.I);this.ya=!!this.l.captionTracks.length;this.Ba=!!this.l.Xi;this.ka="3"==this.u.l;b=a.app.o;c=!(!b||!b.Ik());this.va=!(!b||!b.vh());this.B=this.ka&&c&&!this.na;this.R=!this.B&&this.ka&&this.va&&this.na;this.i=this.D=this.F=this.P=this.ia=null;this.Y=
new O3(this.u);g.I(this,this.Y);c=b=this.g=null;this.B||(b=new g.uo(this.uA,void 0,this),g.I(this,b),c=new g.N(this.yL,2E3,this),g.I(this,c));this.X=b;this.ca=c;this.ba=new g.hs(this);g.I(this,this.ba);this.B||this.ba.K(a,"resize",this.Es);this.ba.K(a,"onPlaybackAudioChange",this.CH);this.ba.K(a,g.jE("captions"),this.CE,this);this.ba.K(a,"crx_captions",this.DE,this);P3(this,Q3(this,"display-settings")||{})},S3=function(a){if(1==a.u.Qf||1==a.l.Qf||"alwayson"==g.LB(a.l,"yt:cc"))return!0;
if(2==a.u.Qf){var b=Q3(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().Lo;return"ON"==c||"on"==g.LB(a.l,"yt:cc")},T3=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Ll||"FORCED_ON"==c.Lo},V3=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ba?!1:a.ya?!1:!0);c=D2(a.i.i,c);for(var d=[a.l.Pf,a.u.Pf,g.LB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(B2(c[f])==d[e])return c[f];return a.D&&a.D.Zo?a.D.Zo:(d=c.find(function(k){return k.isDefault}))?d:c[0]||U3(a)}return null},U3=function(a){return a.D&&a.D.Ll},W3=function(a){var b=U3(a);
return!!b&&a.g==b},X3=function(a,b){for(var c=a.I.app.o.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},Z3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.O=c,a.O&&Y3(a,"module-enabled",!!b));a.g=b;T3(a)&&(a.g=U3(a));a.load()},Apa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.Aq?b.params.Aq:1<b.i.length?1:0){case 1:return new B3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new I3(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new U2(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},P3=function(a,b,c){var d=$3.yb;
a.o={};g.Sa(a.o,$3);a.o.yb={};g.Sa(a.o.yb,d);a.A={yb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;w3.test(f);e.yb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;w3.test(f);e.yb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||$3.windowColor;w3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.yb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.yb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Ke?3:d.bold?1:d.Ke?2:0);f=f.yb;switch(e){case 1:f.bold=!0;delete f.Ke;break;case 2:delete f.bold;f.Ke=!0;break;case 3:f.bold=!0;f.Ke=!0;break;default:delete f.bold,delete f.Ke}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.yb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=$3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.yb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.yb.fontFamily=f;a.loaded&&a.Es();c&&Y3(a,"display-settings",b)},b4=function(a,b){if(b&&!a.F){var c=S2({te:0,
lang:"en"});a.F=[c,new P2(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.wK(a.player,a.F)}else!b&&a.F&&(a4(a,a.F),a.F=null)},a4=function(a,b){g.yK(a.player,b);
(0,g.B)(b,function(c){g.cb(this.H,c)},a);
a.X.xj()},Q3=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},Y3=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.tC.prototype.Zi=g.ca(13,function(){for(var a=g.Id(document,"track",void 0,this.g),b=0;b<a.length;b++)g.$d(a[b])});
g.VW.prototype.Zi=g.ca(12,function(){this.g.Zi()});
g.tC.prototype.Ik=g.ca(11,function(){return!!this.g.textTracks});
g.VW.prototype.Ik=g.ca(10,function(){return this.g.Ik()});
g.tC.prototype.Si=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.VW.prototype.Si=g.ca(8,function(a){this.g.Si(a)});
g.kC.prototype.vh=g.ca(7,function(){});
g.tC.prototype.vh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.VW.prototype.vh=g.ca(5,function(){return this.g.vh()});
g.Hz.prototype.Fq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Ft.prototype.Ul=g.ca(2,function(a){return(a=this.Xf(a))?a.i:0});
g.zw.prototype.Ul=g.ca(1,function(){return 0});
var Bpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,kpa=/#(.)(.)(.)/,jpa=/^#(?:[0-9a-f]{3}){1,2}$/i,w3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(F2,g.H);F2.prototype.Yy=function(){return!1};
F2.prototype.T=function(){this.zg();g.H.prototype.T.call(this)};
g.t(G2,F2);G2.prototype.xq=function(a,b,c){b=this.tj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.zg();this.g=g.Wq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
G2.prototype.yq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())E2(this.i,c.value);a()};
G2.prototype.tj=function(a,b){var c=a.Hb(),d={fmt:b};a.g&&(d.tlang=B2(a));return g.Fq(c,d)};
G2.prototype.zg=function(){this.g&&this.g.abort()};
H2.prototype.contains=function(a){a=g.ob(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
H2.prototype.length=function(){return this.Ta.length/2};
g.t(I2,g.H);g.h=I2.prototype;g.h.T=function(){g.H.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.Zw=function(a){var b=this;if(this.D.Wh())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Eb()&&(b.reset(),b.g=null,J2(b,b.o.getCurrentTime()),b.u.Na(c))});
else J2(this,a)};
g.h.uF=function(){J2(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new H2;this.i&&(this.i.cancel(),this.i=null)};
g.h.qw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Af(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.fi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||K2(this,a),this.g=g.Va(a.g)));this.H.start()};
g.h.YJ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.Gw(a);c?(a=g.Ov(this.l,this.I,{}),b=this.l,g.Jv(b.i,a,c),b.requestId=a.get("req_id"),K2(this,this.l)):(b||null===this.F||(this.B?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.dc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.dc()))),this.i=this.l=null)};
g.t(L2,F2);g.h=L2.prototype;g.h.xq=function(a,b,c){this.zg();b=mpa(this,a.getId());b||(b=a.i,b=this.g.i?N2(this,b,"386"):N2(this,b));if(b){var d=1E3*(b.index.Ul(b.index.je())-b.index.Hc(b.index.je()));this.l=new I2(new g.ev,this.B,b,function(e,f){c(e,a,f,d)},this.A||g.Yu(b.info),(0,g.y)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Yy=function(){var a=this.o;this.o=!1;return a};
g.h.yq=function(a){var b;this.A?b=[new g.Hz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Hz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?M2(this,"386"):M2(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())E2(this.i,c.value);a()};
g.h.zg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.tj=function(){return""};
g.t(O2,F2);O2.prototype.xq=function(a,b,c){b=this.tj(a,b);var d=(0,g.y)(function(e){this.g=null;c(e.responseText,a)},this);
this.zg();this.g=g.Wq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
O2.prototype.yq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Fq(b,c);c=(0,g.y)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
E2(this.i,new g.Hz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.zg();this.g=g.Wq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
O2.prototype.tj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=B2(a));return c=g.Fq(c,d)};
O2.prototype.zg=function(){this.g&&this.g.abort()};var npa=["left","right","center","justify"];var $3={windowColor:"#080808",windowOpacity:0,textAlign:2,Mf:7,Le:50,yg:100,yb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(P2,g.gE);P2.prototype.toString=function(){return g.gE.prototype.toString.call(this)};g.t(Q2,g.gE);Q2.prototype.toString=function(){return g.gE.prototype.toString.call(this)};
var R2=0;g.t(U2,g.W);g.h=U2.prototype;g.h.tF=function(a,b){var c=g.Th(this.element,this.element.parentElement);this.na=a-c.x;this.va=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.sF=function(a,b){var c=g.Wh(this.element),d=a-this.na-.02*this.Ra,e=b-this.va-.02*this.Oa,f=(d+c.width/2)/this.X*3;f=Math.floor(g.sd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.sd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.sd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.sd(c,0,1);this.o.params.Mf=l;this.o.params.yg=c;this.o.params.Le=d;this.l.Mf=l;this.l.yg=c;this.l.Le=d;this.wz()};
g.h.rF=function(){g.ko(this.element,"ytp-dragging")};
g.h.wz=function(){this.rh(this.B)};
g.h.rh=function(a){var b=Math.min(this.tv(),this.X),c=this.qv(),d="";3==this.o.params.te&&(d="rotate(180deg)");g.Ch(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.zo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Le+2;d=this.l.Mf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.yg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ch(this.element,a)};
g.h.zo=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.P||this.B.length>b)b=0,this.P=!1,this.B=[],this.D=this.V=this.R=null,g.Yd(this.A);for(;b<a.length;b++)Y2(this,a[b])};
g.h.tv=function(){return 0};
g.h.qv=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};Z2.prototype.u=function(){};a3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
a3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var b3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];d3.prototype.set=function(a){this.g=a};
d3.prototype.get=function(){return this.g};
e3.prototype.clear=function(){this.g=0};
e3.prototype.update=function(){this.g=2==this.g?1:0};
e3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
f3.prototype.Uf=function(a){this.Ld=a.Ld;this.timestamp=a.timestamp};
f3.prototype.reset=function(){this.timestamp=this.Ld=0};
g3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
g3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Ld?a+"_":a+String.fromCharCode(d.Ld)}a+="\n"}return a};
g3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var rpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],spa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],tpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],upa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];n3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
$2.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(r3,g.H);r3.prototype.reset=function(){};g.t(s3,r3);s3.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
s3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Sa(l,this.l[m]);m=u3(c,"b");null!=m&&(l.bold=
m);m=u3(c,"i");null!=m&&(l.Ke=m);m=u3(c,"u");null!=m&&(l.underline=m);m=v3(c,"et");null!=m&&(l.charEdgeStyle=m);m=v3(c,"of");null!=m&&(l.offset=m);m=x3(c,"bc");null!=m&&(l.background=m);m=x3(c,"ec");null!=m&&(l.pu=m);m=x3(c,"fc");null!=m&&(l.color=m);m=v3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=t3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=t3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=t3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=v3(c,"rb");null!=m&&(l.vk=m);m=v3(c,"hg");null!=m&&
(l.xD=m);c=v3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.YL=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=y3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=z3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=A3(this,d,e,!1);g.I(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=
d.getAttribute("w")||this.u;m=!!u3(d,"a");n=(t3(d,"t")||0)+n;var p=t3(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],z=d.childNodes;z.length&&(this.B=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var E=z[C];0<C&&(m=!0);var F=void 0;1==E.nodeType&&(F=E);if(F&&"s"==F.tagName)if((E=this.l[F.getAttribute("p")])&&1==E.vk){E=n;var K=p,Y=l,Ca=m,ma=r;var wa=F;var Ec=z[C+1];var Rc=
z[C+2],Ub=z[C+3];wa.getAttribute("p");t3(wa,"t");t3(Ec,"t");t3(Rc,"t");t3(Ub,"t");F=g.Vd("RUBY");wa=wa.textContent;var Gf=g.Vd("SPAN");Gf.innerText=wa;F.appendChild(Gf);Ec.getAttribute("p");Gf=g.Vd("RP");wa=Ec.textContent;Gf.innerText=wa;F.appendChild(Gf);Ec=this.l[Rc.getAttribute("p")];wa=Rc.textContent;Rc=g.Vd("RT");Rc.innerText=wa;F.appendChild(Rc);if(4==Ec.vk||7==Ec.vk)g.Ch(F,"ruby-position","over"),g.Ch(F,"-webkit-ruby-position","before");else if(5==Ec.vk||6==Ec.vk)g.Ch(F,"ruby-position","under"),
g.Ch(F,"-webkit-ruby-position","after");Ub.getAttribute("p");wa=Ub.textContent;Ub=g.Vd("RP");Ub.innerText=wa;F.appendChild(Ub);E=new P2(E,K,ma,Y,F,Ca,null);C+=3}else Ub=F,E=n,K=p,Y=l,Ca=m,ma=r,F=Ub.textContent?Ub.textContent:"",wa=this.l[Ub.getAttribute("p")],Ub=t3(Ub,"t")||0,E=new P2(E+Ub,K-Ub,ma,Y,F,Ca,wa);else E=new P2(n,p,r,l,E.textContent||"",m,u);k.push(E);this.i=E}if(0<k.length)for(k[0].windowId==this.u&&(this.g=A3(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=
d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.i.push(k),c.push(k)}e=c}else e=[];return e};g.t(B3,U2);B3.prototype.zo=function(a){var b=this.o.i;U2.prototype.zo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Sa(d,c.i);g.Sa(d,Cpa);var e=c.i;var f=d}Y2(this,c,d)}};
var Cpa={vD:!0};g.t(C3,Z2);C3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+R2++;c=c/1E3-this.B;d=d/1E3-this.B;a=new Q2(c,d-c,5,f,{textAlign:0,Mf:0,Le:2.5*b,yg:5.33*a});e=new P2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(F3,r3);F3.prototype.o=function(a){a=new C3(a,a.byteLength,this.i);if(G3(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=E3(a)*(1E3/45):1==a.version&&(a.o=4294967296*E3(a)+E3(a)),a.A=D3(a);0<a.A;a.A--){var b=D3(a),c=D3(a),d=D3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,ju:c,ku:d,order:b.g.length}))}qpa(this.g,a);return a.l}return[]};
F3.prototype.reset=function(){this.g.clear()};g.t(I3,U2);g.h=I3.prototype;g.h.wz=function(){g.yo(this.ia)};
g.h.dK=function(){g.ko(this.element,"ytp-rollup-mode");this.rh(this.Ga,!0)};
g.h.qv=function(){return this.u?this.I:this.H};
g.h.tv=function(){return this.u?this.H:this.I};
g.h.rh=function(a,b){this.Ga=a;if(this.o.params.uk){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;U2.prototype.rh.call(this,a);zpa(this,b);U2.prototype.rh.call(this,a)}else U2.prototype.rh.call(this,a)};g.t(K3,r3);
K3.prototype.o=function(a,b){for(var c=[],d=a.split(Dpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Epa.test(f)){var l=c4.exec(f);if(l&&4<=l.length){var m=M3(l[1]),n=M3(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var E=C.next();!E.done;E=C.next())if(E=E.value.split(":"),2==E.length){var F=E[1];switch(E[0]){case "line":E=F.split(",");E[0].endsWith("%")&&(z=E[0],l.yg=Number.parseInt(z,10),2==E.length&&(u=E[1].trim()));break;case "position":E=F.split(",");
r=E[0];l.Le=Number.parseInt(r,10);2==E.length&&(p=E[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.yg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Le=0;break;case 1:l.Le=100;break;default:l.Le=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Mf=0>r||8<r?7:r;p=l;f=f.substring(c4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=N3(m,n,5,r),n=new P2(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.i.push(n);else for(u=p.split(Fpa),1==u.length?(p=5,r=N3(m,n,p,r)):(z=p=6,r=Object.assign({Cl:32},r),r=new Q2(m,n,z,"_"+R2++,r)),c.push(r),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(E=g.mo("<html>"+C+"</html>"),E.getElementsByTagName("parsererror").length?
(F=E.createElement("span"),F.appendChild(E.createTextNode(C))):F=E.firstChild,L3(this,z,n-(z-m),p,r,0<l,F,f,c)):z=M3(C)+k}c4.lastIndex=0}}return c};
var Epa=/^NOTE/,Dpa=/(?:\r\n|\r|\n){2,}/,c4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Fpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(O3,g.H);O3.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
O3.prototype.reset=function(){this.g&&this.g.reset()};
O3.prototype.T=function(){this.clear();g.H.prototype.T.call(this)};g.t(R3,g.RK);g.h=R3.prototype;g.h.T=function(){if(this.B||this.R){var a=this.I.app.o;a&&a.Zi()}else b4(this,!1);g.RK.prototype.T.call(this)};
g.h.Ak=function(){return this.ka?this.B||this.R:T3(this)?!0:S3(this)};
g.h.load=function(){g.RK.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.B?X3(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.xq(this.g,"srv3",(0,g.y)(this.KK,this))),this.g&&!W3(this)?this.player.ma("captionschanged",A2(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new L2(this.l.ga,this.player):this.ya?a=new G2(this.u,this.l,this.player.getAudioTrack()):a=new O2(this.l.Xi,this.l.videoId,this.l.Pf||this.u.Pf||
g.LB(this.l,"yt:cc_default_lang")||this.u.Xb,this.l.Jo,this.u);this.i=a;g.I(this,this.i);a.yq((0,g.y)(this.JK,this))}};
g.h.unload=function(){this.B&&this.g?X3(this,!1):(this.ca&&g.zo(this.ca),g.zK(this.player,"captions"),this.H=[],this.i&&this.i.zg(),this.Y.clear(),this.F&&g.wK(this.player,this.F),this.Es());g.RK.prototype.unload.call(this);var a=g.V(this.player.app);a&&a.o&&g.vD(a.o.l);this.player.ma("captionschanged",{})};
g.h.JK=function(){var a;this.O||S3(this)?a=V3(this,this.O):T3(this)&&(a=U3(this));if(this.B||this.R){for(var b=D2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Iz(e),srclang:B2(e),id:e.toString()};this.R||(f.src=this.i.tj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Ud("TRACK",f))}this.I.app.o.Si(c);a=this.I.app.o.ha();this.va&&this.ba.K(a.textTracks,"change",this.LK)}else!this.g&&a&&Z3(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.LK=function(){for(var a=this.I.app.o.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=D2(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&Z3(this,b,!0)};
g.h.fM=function(){!this.g&&this.B||this.unload()};
g.h.KK=function(a,b,c,d){if(a){this.i.Yy()&&(this.H=[],g.zK(this.I,"captions"),this.X.xj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if(!g.v(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Zt(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!H3(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new K3);var z=e.g.o(b,u);.01>Math.random()&&g.Up(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;u=g.mo(z);if(!u||!u.firstChild){var E=Error("Invalid caption track data");
E.params=z;throw E;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){z={};var F=B2(b);F&&(z.lang=F,Bpa.test(F)&&(z.te=1));e.g=new s3(z,e.i)}C=e.g.o(u,c);break b}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=z;throw K;}if("transcript"==u.firstChild.tagName){var Y=Error("Unsupported subtitles format in web player (Format1)");Y.params=z;throw Y;}var Ca=Error("Invalid caption track data");Ca.params=z;throw Ca;}var ma=
C}else{C=a;u=c;F=d;if(!H3(C))throw Error("Invalid binary caption track data");e.g||(e.g=new F3(F,b));ma=e.g.o(C,u)}var wa=ma}catch(Ec){g.O(Ec),e.clear(),wa=[]}else wa=[];g.wK(this.player,wa);!this.O||this.R||W3(this)||g.iz(this.u)||g.jz(this.u)||(g.zo(this.ca),wa=S2({Mf:0,Le:5,yg:5,uk:2,textAlign:0,te:0,lang:"en"}),this.P=[wa],e=["Click "," for settings"],this.ia||(ma=new g.XC(g.YP()),g.I(this,ma),this.ia=ma.element),ma=wa.end-wa.start,(b=g.Iz(this.g))&&this.P.push(new P2(wa.start,ma,0,wa.id,b)),
this.P.push(new P2(wa.start,ma,0,wa.id,e[0]),new P2(wa.start,ma,0,wa.id,this.ia,!0),new P2(wa.start,ma,0,wa.id,e[1],!0)),g.wK(this.player,this.P),g.xo(this.ca));!this.O||this.R||W3(this)||(Y3(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(wa=g.V(this.player.app))&&wa.o&&g.vD(wa.o.l));this.O=!1}};
g.h.CE=function(a){this.H.push(a);this.X.xj()};
g.h.DE=function(a){g.cb(this.H,a);this.i instanceof L2&&this.i.A&&g.yK(this.player,[a]);this.X.xj()};
g.h.sL=function(a){if(a instanceof Q2){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Apa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.yL=function(){a4(this,this.P);this.P=null};
g.h.uA=function(){this.X.stop();g.Zb(this.V);this.H.sort(g.iE);var a=this.H;if(this.F){var b=(0,g.ae)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.B)(a,this.sL,this);g.Kb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.DK(this.player,c.element,4),c.rh(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.CL=function(){P3(this,{},!0)};
g.h.KC=function(){var a=$3.yb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ke?3:a.bold?1:a.Ke?2:0,textOpacity:a.textOpacity,windowColor:$3.windowColor,windowOpacity:$3.windowOpacity};var b=Q3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.zA=function(a,b){var c={};g.Sa(c,Q3(this,"display-settings"));g.Sa(c,a);P3(this,c,b);this.player.N("captionssettingschanged")};
g.h.Es=function(){!this.B&&this.loaded&&(g.Kb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.uA())};
g.h.ac=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.sd(b,-2,4);this.zA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&Z3(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.ub&&Y3(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Oa(b))break;if(g.Yb(b)){Z3(this,null,!0);break}for(var d=D2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?ipa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||Z3(this,c,!0)}else return this.loaded&&this.g&&!W3(this)?A2(this.g):{};return"";case "tracklist":return this.i?(0,g.G)(D2(this.i.i,!(!b||!b.includeAsr)),function(k){return A2(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.B||void 0==b||b4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.ub&&a.push("stickyLoading");return a};
g.h.vj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.kA=function(){this.loaded&&this.g&&!W3(this)?(Y3(this,"module-enabled",!1),this.unload(),T3(this,!0)&&Z3(this,U3(this),!1)):Z3(this,W3(this)||!this.g?V3(this,!0):this.g,!0)};
g.h.CH=function(){var a=W3(this);T3(this,a)?Z3(this,this.player.getAudioTrack().Ll,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Ak()&&(a?Z3(this,V3(this),!1):this.load()))};g.kV.captions=R3;})(_yt_player);
