(function(g){var window=this;var d4=function(a,b,c){var d=b.oa();g.M(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.xc(c?c:"mqdefault.jpg");var f=b instanceof g.jB&&b.lengthSeconds?g.TQ(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.kE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.jB?b.ra:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ti||g.BN("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.wj(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.mE&&(d.playlist_length=b.getLength());a.update(d)},e4=function(a,b){g.bD.call(this,{C:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},f4=function(a){g.W.call(this,{C:"div",
W:["ytp-upnext","ytp-player-content"],L:{"aria-label":"{{aria_label}}"},J:[{C:"div",G:"ytp-cued-thumbnail-overlay-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-upnext-top",J:[{C:"span",G:"ytp-upnext-header",U:"Up Next"},{C:"span",G:"ytp-upnext-title",U:"{{title}}"},{C:"span",G:"ytp-upnext-author",U:"{{author}}"}]},{C:"a",G:"ytp-upnext-autoplay-icon",L:{role:"button",href:"{{url}}","aria-label":"Play next video"},J:[{C:"svg",L:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},J:[{C:"circle",
G:"ytp-svg-autoplay-circle",L:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",G:"ytp-svg-autoplay-ring",L:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",G:"ytp-svg-fill",L:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",G:"ytp-upnext-bottom",J:[{C:"span",G:"ytp-upnext-cancel"},{C:"span",G:"ytp-upnext-paused",U:"Autoplay is paused"}]}]});
this.A=null;var b=this.i["ytp-upnext-cancel"];this.A=new g.W({C:"button",W:["ytp-upnext-cancel-button","ytp-button"],L:{tabindex:"0","aria-label":"Cancel autoplay"},U:"Cancel"});g.I(this,this.A);this.A.da("click",this.HH,this);this.A.g(b);this.l=a;this.I=this.i["ytp-svg-autoplay-ring"];this.D=this.B=this.o=this.u=null;this.F=new g.N(this.Bl,5E3,this);g.I(this,this.F);this.H=0;this.K(this.i["ytp-upnext-autoplay-icon"],"click",this.wJ);this.Xx();this.K(a,"autonavvisibility",this.Xx);this.K(a,"mdxnowautoplaying",
this.KI);this.K(a,"mdxautoplaycanceled",this.LI);this.K(a,"mdxautoplayupnext",this.yA);3==this.l.getPresentingPlayerType()&&(a=(a=g.pK(g.jK(this.l)))?a.IC():null)&&this.yA(a)},g4=function(a,b){if(!a.o){g.iq("a11y-announce","Up Next "+a.u.title);
a.H=g.Q();a.o=new g.N((0,g.y)(a.yo,a,b),25);a.yo(b);var c=b||g.S(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.ko(a.element,"ytp-upnext-autoplay-paused")},i4=function(a){h4(a);
a.H=g.Q();a.yo();g.L(a.element,"ytp-upnext-autoplay-paused")},h4=function(a){a.o&&(a.o.dispose(),a.o=null)},j4=function(a,b){b=void 0===b?!1:b;
if(g.R(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.u.oa(),a.Bl(),a.B=new Notification("Up Next",{body:c.title,icon:c.xc()}),a.D=a.K(a.B,"click",a.oJ),a.F.start())}h4(a);a.l.nextVideo(!1,b)},k4=function(a){e4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.W({C:"div",G:"ytp-subscribe-card",J:[{C:"img",G:"ytp-author-image",L:{src:b.Jd}},{C:"div",G:"ytp-subscribe-card-right",J:[{C:"div",G:"ytp-author-name",U:b.author},{C:"div",G:"html5-subscribe-button-container"}]}]});g.I(this,this.l);this.l.g(this.element);this.o=new g.cW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Jf,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},l4=function(a){var b=
g.X(a),c=g.dx||g.Fh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.W.call(this,{C:"a",W:e,L:{href:"{{url}}",target:d?b.u:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},J:[{C:"div",G:"ytp-videowall-still-image",L:{style:"{{background}}"}},{C:"span",G:"ytp-videowall-still-info",J:[{C:"span",G:"ytp-videowall-still-info-bg",J:[{C:"span",G:"ytp-videowall-still-info-content",L:c,J:[{C:"span",G:"ytp-videowall-still-info-title",U:"{{title}}"},{C:"span",G:"ytp-videowall-still-info-author",
U:"{{author_and_views}}"},{C:"span",G:"ytp-videowall-still-info-live",U:"Live"},{C:"span",G:"ytp-videowall-still-info-duration",U:"{{duration}}"}]}]}]},{C:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",G:"ytp-videowall-still-listlabel-length",J:[" (",{C:"span",U:"{{playlist_length}}"},")"]}]},{C:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],J:[{C:"span",G:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{C:"span",G:"ytp-videowall-still-listlabel-length",U:" (50+)"}]}]});this.A=d;this.l=a;this.o=null;this.u=new g.hs(this);g.I(this,this.u);this.da("click",this.D);this.da("keypress",this.F);this.u.K(a,"videodatachange",this.B);g.X(a).F&&g.oO(a.app.P,this.element,this);this.B()},m4=function(a){g.GK(a.l,a.element);
var b=a.o.oa().videoId,c=a.o.getPlaylistId();g.iY(a.l.app,b,a.o.Xc,c,void 0,void 0,void 0)},n4=function(a){e4.call(this,a,"videowall-endscreen");
this.H=a;this.B=0;this.o=[];this.D=this.u=this.A=null;this.F=this.R=!1;this.P=null;this.ba=new g.hs(this);g.I(this,this.ba);this.I=new g.N(g.Ra(g.L,this.element,"ytp-show-tiles"),0);g.I(this,this.I);var b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-previous"],L:{"aria-label":"Previous"},J:[g.EP()]});g.I(this,b);b.g(this.element);b.da("click",this.hF,this);this.M=new g.XC({C:"div",G:"ytp-endscreen-content"});g.I(this,this.M);this.M.g(this.element);b=new g.W({C:"button",W:["ytp-button","ytp-endscreen-next"],
L:{"aria-label":"Next"},J:[g.FP()]});g.I(this,b);b.g(this.element);b.da("click",this.gF,this);this.l=new f4(a);g.I(this,this.l);g.DK(this.player,this.l.element,4);this.hide()},o4=function(a){return g.EK(a.player)&&a.du()&&!a.D},p4=function(a,b){return(0,g.G)(b.suggestions,function(c){c=g.gS(g.X(a.H),c);
g.I(a,c);return c})},q4=function(a){var b=a.Ie();
b!=a.R&&(a.R=b,a.player.N("autonavvisibility"))},s4=function(a){g.RK.call(this,a);
this.g=null;this.i=new g.hs(this);g.I(this,this.i);this.l=g.X(a);r4(a)?this.g=new n4(this.player):this.l.Ga?this.g=new k4(this.player):this.g=new e4(this.player);g.I(this,this.g);g.DK(this.player,this.g.element,4);this.vz();this.i.K(a,"videodatachange",this.vz,this);this.i.K(a,g.jE("endscreen"),this.wE,this);this.i.K(a,"crx_endscreen",this.xE,this)},r4=function(a){a=g.X(a);
return a.Ba&&!a.Ga};
g.t(e4,g.bD);e4.prototype.create=function(){this.created=!0};
e4.prototype.destroy=function(){this.created=!1};
e4.prototype.du=function(){return!1};
e4.prototype.Ie=function(){return!1};g.t(f4,g.W);g.h=f4.prototype;g.h.Bl=function(){this.B&&(this.F.stop(),this.Na(this.D),this.D=null,this.B.close(),this.B=null)};
g.h.Xx=function(){g.aD(this,this.l.Ie())};
g.h.oJ=function(){window.focus();this.Bl()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.yo=function(a){a=a||g.S(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.Q()-this.H,a);a=Math.min(b/a,1);this.I.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?j4(this,!0):this.o&&this.o.start()};
g.h.wJ=function(a){!g.de(this.A.element,g.Xr(a))&&g.jS(a,this.l)&&j4(this)};
g.h.HH=function(){g.lK(this.l,!0)};
g.h.KI=function(a){this.l.getPresentingPlayerType();this.show();g4(this,a)};
g.h.yA=function(a){this.l.getPresentingPlayerType();this.u&&this.u.oa().videoId==a.oa().videoId||(this.u=a,d4(this,a,"hqdefault.jpg"))};
g.h.LI=function(){this.l.getPresentingPlayerType();h4(this);this.hide()};
g.h.T=function(){h4(this);this.Bl();g.W.prototype.T.call(this)};g.t(k4,e4);g.t(l4,g.W);l4.prototype.D=function(a){g.jS(a,this.l,this.A,this.o.Xc||void 0)&&m4(this)};
l4.prototype.F=function(a){switch(a.keyCode){case 13:case 32:g.bs(a)||(m4(this),g.as(a))}};
l4.prototype.B=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.A=a.Sb?!1:b.i};g.t(n4,e4);g.h=n4.prototype;g.h.create=function(){e4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=p4(this,a),this.u=a);this.Cf();this.ba.K(this.player,"appresize",this.Cf);this.ba.K(this.player,"onVideoAreaChange",this.Cf);this.ba.K(this.player,"videodatachange",this.iF);this.ba.K(this.player,"autonavchange",this.Jq);this.ba.K(this.player,"autonavcancel",this.fF);a=this.u.autonavState;a!=this.P&&this.Jq(a);this.ba.K(this.element,"transitionend",this.MK)};
g.h.destroy=function(){g.js(this.ba);g.sf(this.o);this.o=[];this.A=null;e4.prototype.destroy.call(this);g.ko(this.element,"ytp-show-tiles");this.I.stop();this.P=this.u.autonavState};
g.h.du=function(){return 1!=this.u.autonavState};
g.h.show=function(){e4.prototype.show.call(this);g.ko(this.element,"ytp-show-tiles");g.X(this.player).g?g.yo(this.I):this.I.start();(this.F||this.D&&this.D!=this.u.clientPlaybackNonce)&&g.lK(this.player,!1);o4(this)?(q4(this),2==this.u.autonavState?g.R(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?j4(this.l,!0):g4(this.l):3==this.u.autonavState&&i4(this.l)):(g.lK(this.player,!0),q4(this))};
g.h.hide=function(){e4.prototype.hide.call(this);i4(this.l);q4(this)};
g.h.MK=function(a){g.Xr(a)==this.element&&this.Cf()};
g.h.Cf=function(){if(this.A&&this.A.length){g.L(this.element,"ytp-endscreen-paginate");var a=g.uK(this.H,!0),b=g.qD(this.H);b&&(b=b.zc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,u=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(u)n-=r*m,b+=2;else if(z)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.sd(a.width/m||1,1,1.21);n*=g.sd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.M.element;g.Vh(a,m,n);g.Ch(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.u=f;d4(c,f,"hqdefault.jpg");g.M(this.element,"ytp-endscreen-takeover",o4(this));q4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-
2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.td(p+this.B,l),0!=r){u=this.o[c];u||(u=new l4(this.player),this.o[c]=u,a.appendChild(u.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),E=Math.floor(n*(k+r)/e)-z-4,F=Math.floor(m*(f+r)/b)-C-4;g.Kh(u.element,C,z);g.Vh(u.element,F,E);g.Ch(u.element,"transitionDelay",(k+f)/20+"s");g.M(u.element,"ytp-videowall-still-mini",1==r);g.M(u.element,"ytp-videowall-still-large",2<r);r=u;p=this.A[p];r.o!=p&&(r.o=p,d4(r,p,g.io(r.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Xc)&&p.itct)&&(u=r.l,g.X(u).F&&g.pO(u.app.P,r.element,p));c++}g.M(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.$d(e.element),g.rf(e);this.o.length=c}};
g.h.iF=function(){var a=this.player.getVideoData();this.u!=a&&(this.B=0,this.A=p4(this,a),this.u=a,this.Cf())};
g.h.gF=function(){this.B+=this.o.length;this.Cf()};
g.h.hF=function(){this.B-=this.o.length;this.Cf()};
g.h.JD=function(){return!!this.l.o};
g.h.Jq=function(a){1==a?(this.F=!1,this.D=this.u.clientPlaybackNonce,h4(this.l),this.Fa()&&this.Cf()):(this.F=!0,this.Fa()&&o4(this)&&(2==a?g4(this.l):3==a&&i4(this.l)))};
g.h.fF=function(a){if(a){for(a=0;a<this.o.length;a++)g.HK(this.H,this.o[a].element,!0);this.Jq(1)}else this.D=null,this.F=!1;this.Cf()};
g.h.Ie=function(){return this.Fa()&&o4(this)};g.t(s4,g.RK);g.h=s4.prototype;g.h.Ak=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!r4(this.player)||b;a=a.Kc;var c=g.JX(this.player.app);return b&&!a&&!c};
g.h.Ie=function(){return this.g.Ie()};
g.h.FD=function(){return this.Ie()?this.g.JD():!1};
g.h.T=function(){g.zK(this.player,"endscreen");g.RK.prototype.T.call(this)};
g.h.load=function(){g.RK.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.RK.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.wE=function(a){this.Ak()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.xE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.vz=function(){g.zK(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.gE(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.gE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.wK(this.player,[a,b])};g.kV.endscreen=s4;})(_yt_player);
